<<<<<<< HEAD
<!-- Generated by ::xowiki::ADP_Generator on Tue Sep 22 15:27:59 -03 2020 -->
=======
<<<<<<< HEAD
<<<<<<< HEAD
<!-- Generated by ::xowiki::ADP_Generator on Sun Sep 06 16:19:35 -03 2020 -->
=======
<!-- Generated by ::xowiki::ADP_Generator on Sun Sep 06 16:19:49 -03 2020 -->
>>>>>>> b02b7c49ae92f1c787888a4906a703ea33ef9bbf
=======
<!-- Generated by ::xowiki::ADP_Generator on Tue Sep 15 00:33:05 -03 2020 -->
>>>>>>> 6b4a3bc4f2ee9c33282f65ef4cf42b378a260985
>>>>>>> 4b18b3fb4ffc953322b0066b8493125fef6b4540
<!-- The following DIV is needed for overlib to function! -->
          <div id="overDiv" style="position:absolute; visibility:hidden; z-index:1000;"></div>    
          <div class='xowiki-content'>

 @top_includelets;noquote@
 <if @body.menubarHTML@ not nil><div class='visual-clear'><!-- --></div>@body.menubarHTML;noquote@</if>
 <if @page_context@ not nil><h1>@body.title@ (@page_context@)</h1></if>
 <else><h1>@body.title@</h1></else>
 <if @folderhtml@ not nil> 
 <div class='folders' style=''>@folderhtml;noquote@</div> 
 <div class='content-with-folders'>@content;noquote@</div> 
 </if>
    <else>@content;noquote@</else>

</div> <!-- class='xowiki-content' -->
